#!/bin/bash


cat > ./parser-output/tweets-html/all/index.html << EOF
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <style>
    body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
        font-size: 15px;
    }
    main {
        max-width: 40em;
        margin: auto;
    }
    main img,video {
        max-width: 40em;
        margin-left: -2em;
    }
    </style>
    <title>Andy Balaam Twitter Archive</title>
</head>
<body>
<main>
<h1>Andy Balaam Twitter Archive</h1>

EOF

find ./parser-output/tweets-html/ -name "*.html" \
        | sort \
        | xargs -n 1 ./strip \
        >> ./parser-output/tweets-html/all/index.html

cat >> ./parser-output/tweets-html/all/index.html << EOF

</main>
</body>
</html>
EOF

rsync -r ./parser-output/media/ ./parser-output/tweets-html/all/media/

echo "Now copy ./parser-output/tweets-html/all/ to somewhere on the Internet"
